name: ibp-data-query

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env: 
  nexus_username: ${{ secrets.NEXUS_USERNAME }}
  nexus_password: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  ibp-data-query:
    #runs-on: self-hosted
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Call Maven Workflow
        uses: ./.github/actions/maven-action
        with:
          mavenPomFile: './pom.xml'
          goals: clean package
          #goals: clean package deploy 
          options: '--settings ./settings.xml'
          publishJUnitResults: true
          testResultsFiles: '**\target\surefire-reports\*.xml'
          testRunTitle: 'testHelloWorld'
          allowBrokenSymlinks: true

