name: Main Workflow.

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-called-maven-workflow:
    uses: ./.github/workflows/called_maven_workflow.yml
    with:
      mavenPomFile: './pom.xml'
      options: '--settings settings.xml'
      #options: ''
      testRunTitle: 'IBP Data Query'
    secrets:
      nexus_username: ${{ secrets.NEXUS_USERNAME }}
      nexus_password: ${{ secrets.NEXUS_PASSWORD }}  

