name: ibp-data-query

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env: 
  nexus_username: ${{ secrets.NEXUS_USERNAME }}
  nexus_password: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  ibp-data-query:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Call Maven Workflow
        uses: ./.github/workflows/called_maven_workflow.yml
        with:
          mavenPomFile: './pom.xml'
          goals: clean package
          options: '--settings ./settings.xml'
          testRunTitle: 'IBP Data Query'
          jdkVersionOption: 1.8
