name: maven-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maven-build:
        uses: ./.github/workflows/called_maven_workflow.yml
        with:
          mavenPomFile: './pom.xml'
          goals: clean package
          options: '--settings ./settings.xml'
          testRunTitle: 'IBP Data Query'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkDirectory: 'C:\Program Files\Java\jdk1.8.0_291'
