name: maven-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maven-build:
    runs-on: windows-latest
    steps:

      - name: maven build
        uses: ./.github/workflows/called_maven_workflow.yml
        with:
          mavenPomFile: './pom.xml'
          goals: clean package
          options: '--settings ./settings.xml'
          testRunTitle: 'IBP Data Query'
          jdkVersionOption: 1.8
