name: Training Session

on:
  push:
    branches:
      - feature/JP
  workflow_dispatch:

jobs:
  demo-job:
   runs-on: windows-latest

   steps:
     - name: Print Message
       run: echo "Training Session & Github Actions"
   
