name: Training Session

on:
  push:
    branches:
      - feature/JP
  workflow_dispatch:

jobs:
  demo-job:
   runs-on: windows-latest

   steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    
    - name: Java Version
      run: java -version
   
